[2025-02-04T09:59:54.925+0000] {processor.py:186} INFO - Started process (PID=82) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T09:59:54.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T09:59:54.929+0000] {logging_mixin.py:190} INFO - [2025-02-04T09:59:54.929+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T09:59:55.014+0000] {logging_mixin.py:190} INFO - [2025-02-04T09:59:55.014+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.4', 5672)
[2025-02-04T09:59:55.017+0000] {logging_mixin.py:190} INFO - [2025-02-04T09:59:55.016+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.18.0.6', 56892), raddr=('172.18.0.4', 5672)>
[2025-02-04T09:59:55.019+0000] {logging_mixin.py:190} INFO - [2025-02-04T09:59:55.018+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fe3c6a90e90>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fe3c6a90e90> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T09:59:55.025+0000] {logging_mixin.py:190} INFO - [2025-02-04T09:59:55.025+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fe3c6a90e90> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T09:59:55.027+0000] {logging_mixin.py:190} INFO - [2025-02-04T09:59:55.026+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fe3c6a90e90> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T09:59:55.028+0000] {logging_mixin.py:190} INFO - [2025-02-04T09:59:55.027+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fe3c6a90e90> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T09:59:55.029+0000] {logging_mixin.py:190} INFO - [2025-02-04T09:59:55.029+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T09:59:55.034+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T09:59:55.036+0000] {logging_mixin.py:190} INFO - Processing report for adarshchintada2@gmail.com with Excel File: /opt/airflow/dags/Flash_Report_12-01-2024.xlsx
[2025-02-04T10:00:17.771+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:00:17.765+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 68, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 851, in process_data_events
    self._dispatch_channel_events()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 567, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1510, in _dispatch_events
    consumer_info.on_message_callback(self, evt.method,
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 39, in process_report_request
    with open(report_file_path, "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/reports/adarshchintada2_gmail.com.json'
[2025-02-04T10:00:17.773+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:00:17.817+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 22.902 seconds
[2025-02-04T10:10:06.626+0000] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:10:06.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T10:10:06.633+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:10:06.632+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:10:06.708+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:10:06.708+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.4', 5672)
[2025-02-04T10:10:06.710+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:10:06.709+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.18.0.6', 59594), raddr=('172.18.0.4', 5672)>
[2025-02-04T10:10:06.711+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:10:06.711+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de0dd850>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de0dd850> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T10:10:06.718+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:10:06.717+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de0dd850> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:10:06.719+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:10:06.719+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de0dd850> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:10:06.720+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:10:06.720+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de0dd850> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:10:06.721+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:10:06.721+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T10:10:06.734+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T10:10:36.648+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:10:36.647+0000] {timeout.py:68} ERROR - Process timed out, PID: 56
[2025-02-04T10:10:36.657+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:10:36.648+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 72, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 579, in poll
    self._poller.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 56
[2025-02-04T10:10:36.659+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:10:36.710+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.096 seconds
[2025-02-04T10:11:07.210+0000] {processor.py:186} INFO - Started process (PID=85) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:11:07.211+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T10:11:07.213+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:11:07.213+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:11:07.270+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:11:07.269+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.4', 5672)
[2025-02-04T10:11:07.271+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:11:07.271+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.18.0.6', 40354), raddr=('172.18.0.4', 5672)>
[2025-02-04T10:11:07.273+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:11:07.272+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efb9ba40>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efb9ba40> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T10:11:07.277+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:11:07.277+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efb9ba40> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:11:07.278+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:11:07.278+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efb9ba40> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:11:07.279+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:11:07.279+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efb9ba40> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:11:07.280+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:11:07.280+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T10:11:07.282+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T10:11:37.227+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:11:37.227+0000] {timeout.py:68} ERROR - Process timed out, PID: 85
[2025-02-04T10:11:37.237+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:11:37.228+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 72, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 579, in poll
    self._poller.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 85
[2025-02-04T10:11:37.238+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:11:37.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.086 seconds
[2025-02-04T10:12:07.509+0000] {processor.py:186} INFO - Started process (PID=94) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:12:07.511+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T10:12:07.514+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:12:07.514+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:12:07.560+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:12:07.560+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.4', 5672)
[2025-02-04T10:12:07.562+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:12:07.561+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.18.0.6', 42240), raddr=('172.18.0.4', 5672)>
[2025-02-04T10:12:07.564+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:12:07.564+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efb01f70>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efb01f70> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T10:12:07.570+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:12:07.569+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efb01f70> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:12:07.571+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:12:07.570+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efb01f70> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:12:07.571+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:12:07.571+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efb01f70> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:12:07.572+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:12:07.572+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T10:12:07.576+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T10:12:37.526+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:12:37.526+0000] {timeout.py:68} ERROR - Process timed out, PID: 94
[2025-02-04T10:12:37.538+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:12:37.527+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 72, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 579, in poll
    self._poller.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 94
[2025-02-04T10:12:37.540+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:12:37.599+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.098 seconds
[2025-02-04T10:13:08.007+0000] {processor.py:186} INFO - Started process (PID=103) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:13:08.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T10:13:08.010+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:13:08.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:13:08.049+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:13:08.049+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.4', 5672)
[2025-02-04T10:13:08.051+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:13:08.050+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.18.0.6', 52188), raddr=('172.18.0.4', 5672)>
[2025-02-04T10:13:08.052+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:13:08.052+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efa7bc20>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efa7bc20> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T10:13:08.057+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:13:08.057+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efa7bc20> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:13:08.058+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:13:08.058+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efa7bc20> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:13:08.058+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:13:08.058+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efa7bc20> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:13:08.059+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:13:08.059+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T10:13:08.061+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T10:13:38.017+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:13:38.017+0000] {timeout.py:68} ERROR - Process timed out, PID: 103
[2025-02-04T10:13:38.025+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:13:38.018+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 72, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 579, in poll
    self._poller.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 103
[2025-02-04T10:13:38.026+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:13:38.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.086 seconds
[2025-02-04T10:14:08.423+0000] {processor.py:186} INFO - Started process (PID=112) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:14:08.424+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T10:14:08.427+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:14:08.426+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:14:08.479+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:14:08.479+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.4', 5672)
[2025-02-04T10:14:08.481+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:14:08.480+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.18.0.6', 41540), raddr=('172.18.0.4', 5672)>
[2025-02-04T10:14:08.483+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:14:08.482+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efa7bd10>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efa7bd10> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T10:14:08.488+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:14:08.488+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efa7bd10> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:14:08.489+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:14:08.489+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efa7bd10> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:14:08.490+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:14:08.490+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efa7bd10> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:14:08.492+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:14:08.491+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T10:14:08.496+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T10:14:38.437+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:14:38.437+0000] {timeout.py:68} ERROR - Process timed out, PID: 112
[2025-02-04T10:14:38.447+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:14:38.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 72, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 579, in poll
    self._poller.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 112
[2025-02-04T10:14:38.448+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:14:38.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.088 seconds
[2025-02-04T10:15:08.786+0000] {processor.py:186} INFO - Started process (PID=121) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:15:08.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T10:15:08.790+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:15:08.790+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:15:08.833+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:15:08.833+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.4', 5672)
[2025-02-04T10:15:08.834+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:15:08.834+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.18.0.6', 35018), raddr=('172.18.0.4', 5672)>
[2025-02-04T10:15:08.836+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:15:08.835+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de0f6360>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de0f6360> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T10:15:08.841+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:15:08.840+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de0f6360> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:15:08.841+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:15:08.841+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de0f6360> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:15:08.842+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:15:08.842+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de0f6360> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:15:08.843+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:15:08.842+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T10:15:08.845+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T10:15:38.800+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:15:38.799+0000] {timeout.py:68} ERROR - Process timed out, PID: 121
[2025-02-04T10:15:38.806+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:15:38.800+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 72, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 579, in poll
    self._poller.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 121
[2025-02-04T10:15:38.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:15:38.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.074 seconds
[2025-02-04T10:16:09.240+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:16:09.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T10:16:09.244+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:16:09.244+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:16:09.298+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:16:09.298+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.4', 5672)
[2025-02-04T10:16:09.300+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:16:09.300+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.18.0.6', 42958), raddr=('172.18.0.4', 5672)>
[2025-02-04T10:16:09.302+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:16:09.302+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efb03410>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efb03410> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T10:16:09.308+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:16:09.307+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efb03410> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:16:09.309+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:16:09.309+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efb03410> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:16:09.310+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:16:09.310+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efb03410> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:16:09.311+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:16:09.311+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T10:16:09.314+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T10:16:39.255+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:16:39.255+0000] {timeout.py:68} ERROR - Process timed out, PID: 130
[2025-02-04T10:16:39.265+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:16:39.256+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 72, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 579, in poll
    self._poller.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 130
[2025-02-04T10:16:39.266+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:16:39.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.114 seconds
[2025-02-04T10:17:09.523+0000] {processor.py:186} INFO - Started process (PID=139) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:17:09.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T10:17:09.527+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:17:09.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:17:09.570+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:17:09.570+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.4', 5672)
[2025-02-04T10:17:09.572+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:17:09.571+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.18.0.6', 38096), raddr=('172.18.0.4', 5672)>
[2025-02-04T10:17:09.573+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:17:09.573+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efac08c0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efac08c0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T10:17:09.578+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:17:09.578+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efac08c0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:17:09.579+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:17:09.579+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efac08c0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:17:09.580+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:17:09.580+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48efac08c0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:17:09.580+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:17:09.580+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T10:17:09.583+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T10:17:39.538+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:17:39.538+0000] {timeout.py:68} ERROR - Process timed out, PID: 139
[2025-02-04T10:17:39.547+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:17:39.539+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 72, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 579, in poll
    self._poller.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 139
[2025-02-04T10:17:39.548+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:17:39.597+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.081 seconds
[2025-02-04T10:18:09.670+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:18:09.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T10:18:09.674+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:09.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:18:09.728+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:09.728+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.4', 5672)
[2025-02-04T10:18:09.730+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:09.729+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.18.0.6', 34038), raddr=('172.18.0.4', 5672)>
[2025-02-04T10:18:09.731+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:09.731+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48f30d96d0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48f30d96d0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T10:18:09.738+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:09.737+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48f30d96d0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:18:09.739+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:09.739+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48f30d96d0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:18:09.740+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:09.740+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48f30d96d0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:18:09.740+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:09.740+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T10:18:09.743+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T10:18:39.689+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:39.689+0000] {timeout.py:68} ERROR - Process timed out, PID: 148
[2025-02-04T10:18:39.698+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:39.690+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 72, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 579, in poll
    self._poller.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 148
[2025-02-04T10:18:39.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:18:39.758+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.095 seconds
[2025-02-04T10:18:51.596+0000] {processor.py:186} INFO - Started process (PID=157) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:18:51.597+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T10:18:51.599+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:51.599+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:18:51.669+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:51.669+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.4', 5672)
[2025-02-04T10:18:51.671+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:51.671+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.18.0.6', 37972), raddr=('172.18.0.4', 5672)>
[2025-02-04T10:18:51.673+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:51.673+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de00f020>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de00f020> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T10:18:51.679+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:51.678+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de00f020> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:18:51.680+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:51.679+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de00f020> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:18:51.680+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:51.680+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de00f020> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:18:51.681+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:18:51.681+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T10:18:51.685+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T10:19:21.615+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:19:21.614+0000] {timeout.py:68} ERROR - Process timed out, PID: 157
[2025-02-04T10:19:21.671+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:19:21.616+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 72, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 579, in poll
    self._poller.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 157
[2025-02-04T10:19:21.673+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:19:21.736+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.148 seconds
[2025-02-04T10:19:52.084+0000] {processor.py:186} INFO - Started process (PID=166) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:19:52.086+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T10:19:52.089+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:19:52.089+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:19:52.159+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:19:52.158+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.4', 5672)
[2025-02-04T10:19:52.161+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:19:52.160+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.18.0.6', 59248), raddr=('172.18.0.4', 5672)>
[2025-02-04T10:19:52.164+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:19:52.163+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de02f0e0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de02f0e0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T10:19:52.172+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:19:52.169+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de02f0e0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:19:52.189+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:19:52.188+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de02f0e0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:19:52.192+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:19:52.192+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48de02f0e0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:19:52.195+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:19:52.194+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T10:19:52.200+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T10:21:11.164+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:21:11.167+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T10:21:11.175+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:21:11.175+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:21:11.236+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:21:11.236+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.4', 5672)
[2025-02-04T10:21:11.238+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:21:11.237+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.18.0.6', 46170), raddr=('172.18.0.4', 5672)>
[2025-02-04T10:21:11.240+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:21:11.240+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f6b34d92c60>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f6b34d92c60> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T10:21:11.246+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:21:11.246+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f6b34d92c60> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:21:11.247+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:21:11.247+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f6b34d92c60> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:21:11.249+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:21:11.249+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f6b34d92c60> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:21:11.250+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:21:11.250+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T10:21:11.261+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T10:21:41.192+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:21:41.192+0000] {timeout.py:68} ERROR - Process timed out, PID: 57
[2025-02-04T10:21:41.205+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:21:41.193+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 72, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 579, in poll
    self._poller.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 57
[2025-02-04T10:21:41.207+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:21:41.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.116 seconds
[2025-02-04T10:32:32.923+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:32:32.925+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T10:32:32.930+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:32:32.929+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:32:33.002+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:32:33.002+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.4', 5672)
[2025-02-04T10:32:33.005+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:32:33.004+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.18.0.6', 48546), raddr=('172.18.0.4', 5672)>
[2025-02-04T10:32:33.006+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:32:33.006+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7febae8eed80>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7febae8eed80> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T10:32:33.012+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:32:33.011+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7febae8eed80> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:32:33.013+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:32:33.013+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7febae8eed80> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:32:33.014+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:32:33.014+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7febae8eed80> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T10:32:33.015+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:32:33.015+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T10:32:33.035+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T10:33:02.942+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:33:02.942+0000] {timeout.py:68} ERROR - Process timed out, PID: 57
[2025-02-04T10:33:02.954+0000] {logging_mixin.py:190} INFO - [2025-02-04T10:33:02.943+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 72, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 579, in poll
    self._poller.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 57
[2025-02-04T10:33:02.955+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T10:33:03.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.107 seconds
[2025-02-04T11:17:00.749+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T11:17:00.752+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T11:17:00.756+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:17:00.755+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T11:17:00.860+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:17:00.859+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.4', 5672)
[2025-02-04T11:17:00.862+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:17:00.861+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.18.0.5', 43916), raddr=('172.18.0.4', 5672)>
[2025-02-04T11:17:00.863+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:17:00.863+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f52b00cad50>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f52b00cad50> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T11:17:00.871+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:17:00.870+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f52b00cad50> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T11:17:00.872+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:17:00.872+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f52b00cad50> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T11:17:00.873+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:17:00.873+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f52b00cad50> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T11:17:00.880+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:17:00.874+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T11:17:00.888+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T11:17:00.889+0000] {logging_mixin.py:190} INFO - Processing report for adarshchintada2@gmail.com with Excel File: /opt/airflow/dags/Flash_Report_12-01-2024.xlsx
[2025-02-04T11:17:30.772+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:17:30.772+0000] {timeout.py:68} ERROR - Process timed out, PID: 57
[2025-02-04T11:17:30.795+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:17:30.776+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 72, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 851, in process_data_events
    self._dispatch_channel_events()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 567, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1510, in _dispatch_events
    consumer_info.on_message_callback(self, evt.method,
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 34, in process_report_request
    response = requests.post(REPORT_GENERATOR_API_URL, files=files, data=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 57
[2025-02-04T11:17:30.796+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T11:17:30.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.113 seconds
[2025-02-04T12:33:09.575+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T12:33:09.578+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T12:33:09.582+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:33:09.582+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T12:33:09.673+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:33:09.673+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.4', 5672)
[2025-02-04T12:33:09.676+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:33:09.675+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.18.0.6', 35760), raddr=('172.18.0.4', 5672)>
[2025-02-04T12:33:09.677+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:33:09.677+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fd9abb95f70>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fd9abb95f70> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T12:33:09.685+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:33:09.684+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fd9abb95f70> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T12:33:09.687+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:33:09.687+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fd9abb95f70> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T12:33:09.688+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:33:09.688+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fd9abb95f70> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T12:33:09.689+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:33:09.689+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T12:33:09.708+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T12:33:39.599+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:33:39.599+0000] {timeout.py:68} ERROR - Process timed out, PID: 57
[2025-02-04T12:33:39.611+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:33:39.600+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 77, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 579, in poll
    self._poller.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 57
[2025-02-04T12:33:39.613+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T12:33:39.675+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.111 seconds
[2025-02-04T12:59:37.812+0000] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T12:59:37.814+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T12:59:37.818+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:59:37.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T12:59:37.878+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:59:37.877+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.19.0.4', 5672)
[2025-02-04T12:59:37.880+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:59:37.879+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.19.0.6', 38192), raddr=('172.19.0.4', 5672)>
[2025-02-04T12:59:37.882+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:59:37.882+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2818aecf80>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2818aecf80> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T12:59:37.889+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:59:37.888+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2818aecf80> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T12:59:37.890+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:59:37.889+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2818aecf80> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T12:59:37.891+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:59:37.890+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2818aecf80> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T12:59:37.891+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:59:37.891+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T12:59:37.906+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T13:00:07.831+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:00:07.831+0000] {timeout.py:68} ERROR - Process timed out, PID: 56
[2025-02-04T13:00:07.844+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:00:07.832+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 77, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 579, in poll
    self._poller.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 56
[2025-02-04T13:00:07.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T13:00:07.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.095 seconds
[2025-02-04T13:19:13.052+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T13:19:13.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T13:19:13.058+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:19:13.057+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T13:19:13.135+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:19:13.134+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.19.0.4', 5672)
[2025-02-04T13:19:13.137+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:19:13.136+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.19.0.6', 47982), raddr=('172.19.0.4', 5672)>
[2025-02-04T13:19:13.138+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:19:13.138+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f9a8ccd4770>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f9a8ccd4770> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T13:19:13.143+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:19:13.143+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f9a8ccd4770> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T13:19:13.144+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:19:13.144+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f9a8ccd4770> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T13:19:13.145+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:19:13.145+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f9a8ccd4770> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T13:19:13.146+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:19:13.146+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T13:19:13.161+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T13:19:43.072+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:19:43.072+0000] {timeout.py:68} ERROR - Process timed out, PID: 57
[2025-02-04T13:19:43.080+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:19:43.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 87, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 579, in poll
    self._poller.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 57
[2025-02-04T13:19:43.081+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T13:19:43.121+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.077 seconds
[2025-02-04T13:27:37.463+0000] {processor.py:186} INFO - Started process (PID=58) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T13:27:37.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T13:27:37.473+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:27:37.472+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T13:27:37.593+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:27:37.593+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.19.0.3', 5672)
[2025-02-04T13:27:37.595+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:27:37.595+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('172.19.0.6', 56584), raddr=('172.19.0.3', 5672)>
[2025-02-04T13:27:37.598+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:27:37.597+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7efefee17bc0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7efefee17bc0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-04T13:27:37.608+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:27:37.607+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7efefee17bc0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T13:27:37.610+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:27:37.609+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7efefee17bc0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T13:27:37.611+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:27:37.610+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7efefee17bc0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-04T13:27:37.612+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:27:37.612+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-04T13:27:37.630+0000] {logging_mixin.py:190} INFO - Waiting for report requests...
[2025-02-04T13:28:07.495+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:28:07.495+0000] {timeout.py:68} ERROR - Process timed out, PID: 58
[2025-02-04T13:28:07.508+0000] {logging_mixin.py:190} INFO - [2025-02-04T13:28:07.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/rabbitmq_consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/rabbitmq_consumer.py", line 87, in <module>
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 579, in poll
    self._poller.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/rabbitmq_consumer.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 58
[2025-02-04T13:28:07.510+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T13:28:07.580+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 30.131 seconds
[2025-02-04T14:13:23.638+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T14:13:23.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/rabbitmq_consumer.py for tasks to queue
[2025-02-04T14:13:23.646+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:13:23.646+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T14:13:23.732+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:13:23.731+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
[2025-02-04T14:13:23.733+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:13:23.733+0000] {io_services_utils.py:349} ERROR - Socket failed to connect: <socket.socket fd=19, family=10, type=1, proto=6, laddr=('::1', 52738, 0, 0)>; error=111 (Connection refused)
[2025-02-04T14:13:23.735+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:13:23.734+0000] {connection_workflow.py:375} ERROR - TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0))
[2025-02-04T14:13:23.736+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:13:23.735+0000] {connection_workflow.py:291} ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
[2025-02-04T14:13:23.737+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:13:23.737+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
[2025-02-04T14:13:23.739+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:13:23.739+0000] {io_services_utils.py:349} ERROR - Socket failed to connect: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('127.0.0.1', 46510)>; error=111 (Connection refused)
[2025-02-04T14:13:23.740+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:13:23.740+0000] {connection_workflow.py:375} ERROR - TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 5672))
[2025-02-04T14:13:23.741+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:13:23.740+0000] {connection_workflow.py:291} ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
[2025-02-04T14:13:23.742+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:13:23.741+0000] {connection_workflow.py:746} ERROR - AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused').
[2025-02-04T14:13:23.743+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:13:23.742+0000] {connection_workflow.py:723} ERROR - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
[2025-02-04T14:13:23.744+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:13:23.743+0000] {blocking_connection.py:450} ERROR - Connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
[2025-02-04T14:13:23.749+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:13:23.745+0000] {blocking_connection.py:457} ERROR - Error in _create_connection().
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
[2025-02-04T14:13:23.750+0000] {logging_mixin.py:190} INFO - RabbitMQ Connection Error: 
[2025-02-04T14:13:23.751+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/rabbitmq_consumer.py
[2025-02-04T14:13:23.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/rabbitmq_consumer.py took 0.190 seconds
